import Head from "next/head";
import { createClient } from "contentful";
import { useEffect, useRef, useState, forwardRef } from "react";
import ProductList from "../components/productList/ProductList";
import Sections from "../components/Sections";
import HeroSection from "../components/HeroSection";
import { useProductsStore } from "../store/productsStore";
import { Box, Text } from "@chakra-ui/react";
import { Image, Container } from "@chakra-ui/react";

export default function Home({ retriveProducts }) {
  const [products, setproducts] = useState(retriveProducts);

  const getProducts = useProductsStore((state) => state.getProducts);

  const sectionRefCake = useRef();
  const sectionRefFlower = useRef();

  useEffect(() => {
    getProducts(products);
  }, [products]);

  const handleScrollCakesToView = () => {
    sectionRefCake.current.scrollIntoView({ behavior: "smooth" });
  };
  const handleScrollFlowersToView = () => {
    sectionRefFlower.current.scrollIntoView({
      behavior: "smooth",
    });
  };

  return (
    <div>
      <Head>
        <title>grandma floral & cakes</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <Container maxW="container.lg" position="relative" mb="4rem">
          <Image width="100%" src="/image/madeaPhoto.jpeg" />
          <Box
            position="absolute"
            bottom="0"
            color="whiteAlpha.900"
            width="80%"
            height="150px"
            backgroundColor="blackAlpha.600"
            fontWeight="bolder"
          >
            <Text
              as="h2"
              fontSize="2rem"
              textAlign="center"
              textTransform="uppercase"
              letterSpacing="3px"
            >
              Grandma welcomes you
            </Text>
            <Text
              as="h2"
              textAlign="center"
              px="1rem"
              fontWeight="light"
              fontSize="1.2rem"
            >
              I serve you with home grown flowers and that special cake you have
              always wanted for that special day
            </Text>
          </Box>
        </Container>
        <HeroSection
          handleScrollCakesToView={handleScrollCakesToView}
          handleScrollFlowersToView={handleScrollFlowersToView}
        />

        {products && (
          <div>
            <Sections section="Flowers" bg="#E0E0EB" ref={sectionRefFlower}>
              <ProductList products={products} type={"flower"} />
            </Sections>

            <Sections section="cakes" bg="#CCD7DA" ref={sectionRefCake}>
              <ProductList products={products} type={"cake"} />
            </Sections>
          </div>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const client = createClient({
    space: process.env.NEXT_PUBLIC_DATA_SPACE,
    accessToken: process.env.NEXT_PUBLIC_DATA_KEY,
  });
  const products = await client.getEntries({
    content_type: process.env.NEXT_PUBLIC_DATA_CONT_TYPE,
  });
  const retriveProducts = products ? products.items : "no products retirives";
  return {
    props: {
      retriveProducts,
    },
  };
}
