import { Container } from "@chakra-ui/layout";
import Head from "next/head";
import { createClient } from "contentful";
import { useState } from "react";
import ProductList from "../components/productList/ProductList";
import Sections from "../components/Sections";
import HeroSection from "../components/HeroSection";

export default function Home({ retriveProducts }) {
  const [products, setproducts] = useState(retriveProducts);

  return (
    <div>
      <Head>
        <title>grandma floral & cakes</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <HeroSection />

        {products && (
          <div>
            <Sections section="Flowers" bg="pink.100">
              <ProductList products={products} type={"flower"} />
            </Sections>
            <Sections section="cakes" bg="yellow.100">
              <ProductList products={products} type={"cake"} />
            </Sections>
          </div>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const client = createClient({
    space: process.env.NEXT_PUBLIC_DATA_SPACE,
    accessToken: process.env.NEXT_PUBLIC_DATA_KEY,
  });
  const products = await client.getEntries({
    content_type: process.env.NEXT_PUBLIC_DATA_CONT_TYPE,
  });
  const retriveProducts = products ? products.items : "no products retirives";
  return {
    props: {
      retriveProducts,
    },
  };
}
