import Head from "next/head";
import { createClient } from "contentful";
import { useEffect, useState } from "react";
import ProductList from "../components/productList/ProductList";
import Sections from "../components/Sections";
import HeroSection from "../components/HeroSection";
import { useProductsStore } from "../store/productsStore";

export default function Home({ retriveProducts }) {
  const [products, setproducts] = useState(retriveProducts);

  const getProducts = useProductsStore((state) => state.getProducts);

  useEffect(() => {
    getProducts(products);
  }, [products]);

  return (
    <div>
      <Head>
        <title>grandma floral & cakes</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <HeroSection />

        {products && (
          <div>
            <Sections section="Flowers" bg="#E0E0EB">
              <ProductList products={products} type={"flower"} />
            </Sections>
            <Sections section="cakes" bg="#CCD7DA">
              <ProductList products={products} type={"cake"} />
            </Sections>
          </div>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const client = createClient({
    space: process.env.NEXT_PUBLIC_DATA_SPACE,
    accessToken: process.env.NEXT_PUBLIC_DATA_KEY,
  });
  const products = await client.getEntries({
    content_type: process.env.NEXT_PUBLIC_DATA_CONT_TYPE,
  });
  const retriveProducts = products ? products.items : "no products retirives";
  return {
    props: {
      retriveProducts,
    },
  };
}
